// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;

#nullable disable

namespace Online_Mobile_Recharge.Migrations
{
    [DbContext(typeof(MobileRechargeDbContext))]
    [Migration("20260422123000_addPaymentExternalFields")]
    partial class addPaymentExternalFields
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
        }
    }
}

