// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;

#nullable disable

namespace Online_Mobile_Recharge.Migrations
{
    [DbContext(typeof(MobileRechargeDbContext))]
    [Migration("20260423100000_addUserLockFields")]
    partial class addUserLockFields
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
        }
    }
}

